import { Product } from '@/types';

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: '1a2b3c4d-0001-4000-8000-000000000001',
    title: 'Modern Acrylic Kitchen - Matte Grey & Warm Wood',
    slug: 'modern-acrylic-kitchen-grey-wood',
    category: 'kitchens',
    description: 'Custom-designed contemporary kitchen combining Turkish high-gloss Acrylic in elegant matte grey with heat and moisture-treated natural wood accents. Features smart storage solutions, ergonomic workflows, and Austrian Blum soft-close fittings for decades of smooth operation.',
    thumbnail: '/img/1.jpg',
    images: ['/img/1.jpg', '/img/1-1.jpg', '/img/1-2.jpg', '/img/1-3.jpg'],
    specs: {
      material: 'Turkish High-Gloss Scratch-Resistant Acrylic',
      accessories: 'Original Austrian Blum Soft-Close Hinges & Runners',
      countertop: 'Spanish White Quartz Stain-Resistant Stone',
      warranty: '10-Year Comprehensive Certified Warranty',
      location: 'Obour City - 9th District',
      color: 'Matte Grey & Warm Oak Wood'
    },
    price: null,
    featured: true,
    status: 'published',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 7).toISOString(),
  },
  {
    id: '1a2b3c4d-0002-4000-8000-000000000002',
    title: 'Classic Luxury Kitchen - Royal White with Gold Accents',
    slug: 'classic-luxury-white-kitchen',
    category: 'kitchens',
    description: 'A timeless classic masterpiece finished with moisture-resistant oven Duco paint, handcrafted mouldings, and gold brass handles. Equipped with a central island offering generous storage and authentic Italian Carrara marble countertops.',
    thumbnail: '/img/2.jpg',
    images: ['/img/2.jpg', '/img/img-2.jpg', '/img/img-3.jpg'],
    specs: {
      material: 'Natural Red Beech Wood with German HPL Cladding',
      accessories: 'Full Hydraulic Italian Hardware Systems',
      countertop: 'Natural Italian Carrara Marble',
      warranty: '10-Year Certified Warranty',
      location: 'Fifth Settlement, New Cairo',
      color: 'Royal White with Brushed Gold'
    },
    price: null,
    featured: true,
    status: 'published',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 14).toISOString(),
  },
  {
    id: '1a2b3c4d-0003-4000-8000-000000000003',
    title: 'Contemporary Luxury Dressing Room with Profile LED',
    slug: 'modern-luxury-dressing-room',
    category: 'dressing-rooms',
    description: 'Smart walk-in closet and dressing room featuring calculated geometric compartments for apparel, shoes, and luxury accessories. Fitted with reflective bronze securit glass doors and integrated profile LED lighting with automatic motion sensors.',
    thumbnail: '/img/3.jpg',
    images: ['/img/3.jpg', '/img/img-4.jpg', '/img/img-5.jpg'],
    specs: {
      material: 'High-Density Imported Counter Wood with HPL Finish',
      lighting: 'Concealed LED Profile with Door Motion Sensors',
      accessories: 'Heavy-Duty Hydraulic Drawer Runners & Organizers',
      warranty: '5-Year Certified Warranty',
      location: 'Nasr City, Cairo',
      color: 'Dark Anthracite with Bronze Glass'
    },
    price: null,
    featured: true,
    status: 'published',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 21).toISOString(),
  },
  {
    id: '1a2b3c4d-0004-4000-8000-000000000004',
    title: 'Modern Living Room TV Unit & Architectural Wall Paneling',
    slug: 'modern-tv-unit-living-room',
    category: 'living-rooms',
    description: 'Integrated wall decor and floating TV console featuring UV marble alternative and WPC fluted wood panels. Ambient warm lighting and floating storage compartments deliver an upscale hotel-suite ambiance to your lounge.',
    thumbnail: '/img/img-6.jpg',
    images: ['/img/img-6.jpg', '/img/img-7.jpg'],
    specs: {
      material: 'Turkish UV Marble Alternative & WPC Fluted Wood Panels',
      lighting: 'Concealed Warm White LED 3000K',
      accessories: 'Heavy-Duty Wall Mounts & Hidden Cable Routing',
      warranty: '3-Year Certified Warranty',
      location: 'Sheikh Zayed City',
      color: 'Calacatta White & Natural Walnut'
    },
    price: null,
    featured: false,
    status: 'published',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 30).toISOString(),
  },
  {
    id: '1a2b3c4d-0005-4000-8000-000000000005',
    title: 'PolyLac High-Gloss Modern Kitchen - Heat & Steam Proof',
    slug: 'polylac-modern-kitchen',
    category: 'kitchens',
    description: 'Crafted with premium Korean PolyLac boards engineered to withstand 100% of moisture, steam, and everyday scratches. Open-plan layout configured strictly around the ergonomic work triangle to maximize every inch of functional space.',
    thumbnail: '/img/portfolio-1.jpg',
    images: ['/img/portfolio-1.jpg', '/img/portfolio-2.jpg', '/img/portfolio-3.jpg'],
    specs: {
      material: 'Korean Multi-Layer Scratch-Proof PolyLac',
      countertop: 'Indian Double Black Anti-Bacterial Granite',
      accessories: 'Italian FGV Hydraulic Soft-Close Hinges',
      warranty: '10-Year Comprehensive Certified Warranty',
      location: 'Heliopolis, Cairo',
      color: 'Cappuccino Beige & Pitch Black'
    },
    price: null,
    featured: true,
    status: 'published',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 40).toISOString(),
  },
  {
    id: '1a2b3c4d-0006-4000-8000-000000000006',
    title: 'Bespoke Dining Buffet & Entrance Console Unit',
    slug: 'bespoke-dining-buffet-console',
    category: 'furniture',
    description: 'Fully customized architectural cabinetry featuring European oak veneer, brushed brass inlay accents, and Blum soft-close storage compartments crafted to exact blueprints.',
    thumbnail: '/img/portfolio-4.jpg',
    images: ['/img/portfolio-4.jpg', '/img/portfolio-5.jpg'],
    specs: {
      material: 'Natural European Oak Veneer & Brushed Brass',
      accessories: 'Blum Tip-On & Soft-Close Storage Runners',
      countertop: 'Sintered Stone Countertop',
      warranty: '5-Year Certified Warranty',
      location: 'New Cairo Showroom',
      color: 'Warm Natural Oak & Brushed Gold'
    },
    price: null,
    featured: true,
    status: 'published',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 45).toISOString(),
  },
  {
    id: '1a2b3c4d-0007-4000-8000-000000000007',
    title: 'Walk-In Master Dressing Suite with Smoked Glass Doors',
    slug: 'master-dressing-room-smoked-glass',
    category: 'dressing-rooms',
    description: 'Luxury walk-in dressing suite with Italian aluminum profile doors, tinted smoked securit glass, integrated central jewelry island, and motion-activated sensor lighting.',
    thumbnail: '/img/img-4.jpg',
    images: ['/img/img-4.jpg', '/img/img-5.jpg', '/img/portfolio-2.jpg'],
    specs: {
      material: 'High-Density Moisture-Resistant HPL & Italian Aluminum Profiles',
      lighting: 'Integrated 3000K Warm LED Sensor Strips',
      accessories: 'Heavy-Duty Concealed Hydraulic Runners',
      warranty: '10-Year Certified Warranty',
      location: 'Obour City Showroom',
      color: 'Smoked Bronze & Matte Graphite'
    },
    price: null,
    featured: true,
    status: 'published',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 50).toISOString(),
  }
];

export const CATEGORIES = [
  { id: 'all', nameAr: 'All Projects', nameEn: 'All Projects' },
  { id: 'kitchens', nameAr: 'Modern Kitchens', nameEn: 'Modern Kitchens' },
  { id: 'dressing-rooms', nameAr: 'Dressing Rooms', nameEn: 'Dressing Rooms' },
  { id: 'living-rooms', nameAr: 'Living Rooms & Decor', nameEn: 'Living Rooms & Decor' },
  { id: 'bedrooms', nameAr: 'Bedrooms', nameEn: 'Bedrooms' },
  { id: 'furniture', nameAr: 'Custom Furniture', nameEn: 'Custom Furniture' },
];
